// This file was generated by rive_viewmodel_generator
// Do not edit this file manually
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: unused_import
// ignore_for_file: depend_on_referenced_packages
import 'dart:async';
import 'dart:ui';
import 'package:rive/rive.dart';
import 'package:rive_viewmodel/rive_viewmodel.dart';

enum FrontCardStateMachine {
  stateMachine1('State Machine 1');

  const FrontCardStateMachine(this.name);
  final String name;
}

enum BackCardStateMachine {
  stateMachine1('State Machine 1');

  const BackCardStateMachine(this.name);
  final String name;
}

enum CardStateMachine {
  SmCard('SmCard');

  const CardStateMachine(this.name);
  final String name;
}

sealed class _SealedArtboard {
  String get name;
}

abstract interface class CardStep2Artboard {
  static const frontCard = _FrontCard();
  static const backCard = _BackCard();
  static const card = _Card();
}

class _FrontCard implements _SealedArtboard {
  const _FrontCard();

  @override
  String get name => 'FrontCard';

  FrontCardStateMachine get stateMachine1 =>
      FrontCardStateMachine.stateMachine1;
}

class _BackCard implements _SealedArtboard {
  const _BackCard();

  @override
  String get name => 'BackCard';

  BackCardStateMachine get stateMachine1 => BackCardStateMachine.stateMachine1;
}

class _Card implements _SealedArtboard {
  const _Card();

  @override
  String get name => 'Card';

  CardStateMachine get SmCard => CardStateMachine.SmCard;
}

class VmCardViewModel implements RiveViewModel {
  VmCardViewModel._(this._viewModel);

  factory VmCardViewModel.fromViewModel(ViewModelInstance viewModel) =
      VmCardViewModel._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<String, StreamController<dynamic>> _streamControllers = {};

  bool get isFaceVisible => _viewModel.boolean('isFaceVisible')!.value;

  set isFaceVisible(bool value) =>
      _viewModel.boolean('isFaceVisible')!.value = value;

  Stream<bool> get isFaceVisibleStream {
    return (_streamControllers['isFaceVisible'] ??= () {
          final controller = StreamController<bool>.broadcast();
          _streamControllers['isFaceVisible'] = controller;
          final property = _viewModel.boolean('isFaceVisible')!;
          void valueListener(bool value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<bool>;
  }

  void triggerSwitchToBack() => _viewModel.trigger('switchToBack')!.trigger();

  void triggerSwitchToFace() => _viewModel.trigger('switchToFace')!.trigger();

  void triggerFlip() => _viewModel.trigger('triggerFlip')!.trigger();

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}
