// This file was generated by rive_viewmodel_generator
// Do not edit this file manually
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: unused_import
// ignore_for_file: depend_on_referenced_packages
import 'dart:async';
import 'dart:ui';
import 'package:flutter/painting.dart';
import 'package:rive/rive.dart';
import 'package:rive_viewmodel/rive_viewmodel.dart';

enum CardSymbol { heart, diamond, spade, club }

enum BackCardStateMachine {
  SmBackCard('SmBackCard');

  const BackCardStateMachine(this.name);
  final String name;
}

enum FrontCardStateMachine {
  SmFrontCard('SmFrontCard');

  const FrontCardStateMachine(this.name);
  final String name;
}

enum CardStateMachine {
  SmCard('SmCard');

  const CardStateMachine(this.name);
  final String name;
}

sealed class _SealedArtboard {
  String get name;
}

abstract interface class CardStep3Artboard {
  static const backCard = _BackCard();
  static const frontCard = _FrontCard();
  static const card = _Card();
}

class _BackCard implements _SealedArtboard {
  const _BackCard();

  @override
  String get name => 'BackCard';

  BackCardStateMachine get SmBackCard => BackCardStateMachine.SmBackCard;
}

class _FrontCard implements _SealedArtboard {
  const _FrontCard();

  @override
  String get name => 'FrontCard';

  FrontCardStateMachine get SmFrontCard => FrontCardStateMachine.SmFrontCard;
}

class _Card implements _SealedArtboard {
  const _Card();

  @override
  String get name => 'Card';

  CardStateMachine get SmCard => CardStateMachine.SmCard;
}

class VmFrontCardViewModel implements RiveViewModel {
  VmFrontCardViewModel._(this._viewModel);

  factory VmFrontCardViewModel.fromViewModel(ViewModelInstance viewModel) =
      VmFrontCardViewModel._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<String, StreamController<dynamic>> _streamControllers = {};

  String get valueCard => _viewModel.string('valueCard')!.value;

  set valueCard(String value) => _viewModel.string('valueCard')!.value = value;

  Stream<String> get valueCardStream {
    return (_streamControllers['valueCard'] ??= () {
          final controller = StreamController<String>.broadcast();
          _streamControllers['valueCard'] = controller;
          final property = _viewModel.string('valueCard')!;
          void valueListener(String value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<String>;
  }

  CardSymbol get cardSymbol => CardSymbol.values.firstWhere(
    (e) => e.name == _viewModel.enumerator('cardSymbol')!.value,
  );

  set cardSymbol(CardSymbol value) =>
      _viewModel.enumerator('cardSymbol')!.value = value.name;

  Stream<CardSymbol> get cardSymbolStream {
    return (_streamControllers['cardSymbol'] ??= () {
          final controller = StreamController<CardSymbol>.broadcast();
          _streamControllers['cardSymbol'] = controller;
          final property = _viewModel.enumerator('cardSymbol')!;
          void valueListener(String value) => controller.add(
            CardSymbol.values.firstWhere((e) => e.name == value),
          );
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<CardSymbol>;
  }

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}

class VmBackCardViewModel implements RiveViewModel {
  VmBackCardViewModel._(this._viewModel);

  factory VmBackCardViewModel.fromViewModel(ViewModelInstance viewModel) =
      VmBackCardViewModel._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<
    String,
    ({
      Completer<ImageInfo> completer,
      ImageStream stream,
      ImageStreamListener listener,
    })
  >
  _pendingImageLoads = {};

  final Map<String, StreamController<dynamic>> _streamControllers = {};
  // ignore: use_setters_to_change_properties
  void updateAssetBg(RenderImage value) =>
      _viewModel.image('assetBg')!.value = value;

  void resetAssetBg() => _viewModel.image('assetBg')!.value = null;

  Future<void> updateAssetBgFromImage({
    required Image image,
    required Factory riveFactory,
    required Rect? srcRect,
  }) => _updateImage(
    image: image,
    propertyName: 'assetBg',
    riveFactory: riveFactory,
    srcRect: srcRect,
  );

  Future<void> updateAssetBgFromImageProvider({
    required ImageProvider imageProvider,
    required Factory riveFactory,
  }) => _updateImageFromImageProvider(
    imageProvider: imageProvider,
    propertyName: 'assetBg',
    riveFactory: riveFactory,
  );

  bool get hasCustomBg => _viewModel.boolean('hasCustomBg')!.value;

  set hasCustomBg(bool value) =>
      _viewModel.boolean('hasCustomBg')!.value = value;

  Stream<bool> get hasCustomBgStream {
    return (_streamControllers['hasCustomBg'] ??= () {
          final controller = StreamController<bool>.broadcast();
          _streamControllers['hasCustomBg'] = controller;
          final property = _viewModel.boolean('hasCustomBg')!;
          void valueListener(bool value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<bool>;
  }

  Color get colorBg => _viewModel.color('colorBg')!.value;

  set colorBg(Color value) => _viewModel.color('colorBg')!.value = value;

  Stream<Color> get colorBgStream {
    return (_streamControllers['colorBg'] ??= () {
          final controller = StreamController<Color>.broadcast();
          _streamControllers['colorBg'] = controller;
          final property = _viewModel.color('colorBg')!;
          void valueListener(Color value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<Color>;
  }

  Future<void> _updateImage({
    required Image image,
    required String propertyName,
    required Factory riveFactory,
    required Rect? srcRect,
  }) async {
    final Rect fullImageRect = Rect.fromLTWH(
      0,
      0,
      image.width.toDouble(),
      image.height.toDouble(),
    );
    final Rect imageRect = srcRect ?? fullImageRect;

    Image? imageToRender;
    Picture? picture;
    try {
      if (imageRect != fullImageRect) {
        final PictureRecorder recorder = PictureRecorder();
        Canvas(recorder).drawImageRect(
          image,
          imageRect,
          Rect.fromLTWH(0, 0, imageRect.width, imageRect.height),
          Paint()..filterQuality = FilterQuality.medium,
        );
        picture = recorder.endRecording();
        imageToRender = await picture.toImage(
          imageRect.width.toInt(),
          imageRect.height.toInt(),
        );
      } else {
        imageToRender = image;
      }
      if (_disposed) return;
      final byteData = await imageToRender.toByteData(
        format: ImageByteFormat.png,
      );
      if (byteData == null || _disposed) {
        return;
      }
      final renderImage = await riveFactory.decodeImage(
        byteData.buffer.asUint8List(),
      );
      if (renderImage == null || _disposed) {
        renderImage?.dispose();
        return;
      }
      _viewModel.image(propertyName)!.value = renderImage;
      renderImage.dispose();
    } finally {
      picture?.dispose();
      if (imageToRender != image) {
        imageToRender?.dispose();
      }
    }
  }

  Future<void> _updateImageFromImageProvider({
    required ImageProvider imageProvider,
    required String propertyName,
    required Factory riveFactory,
  }) async {
    final completer = Completer<ImageInfo>();
    final stream = imageProvider.resolve(ImageConfiguration.empty);
    late final ImageStreamListener listener;
    listener = ImageStreamListener(
      (info, _) {
        stream.removeListener(listener);
        if (completer.isCompleted) {
          info.dispose();
        } else {
          completer.complete(info);
        }
      },
      onError: (error, stackTrace) {
        stream.removeListener(listener);
        if (completer.isCompleted) return;
        completer.completeError(error, stackTrace);
      },
    );

    _cancelPendingImageLoad(propertyName);
    _pendingImageLoads[propertyName] = (
      completer: completer,
      stream: stream,
      listener: listener,
    );
    stream.addListener(listener);

    final ImageInfo imageInfo;
    try {
      imageInfo = await completer.future;
    } catch (_) {
      return;
    } finally {
      _pendingImageLoads.remove(propertyName);
    }

    if (_disposed) {
      imageInfo.dispose();
      return;
    }

    try {
      final byteData = await imageInfo.image.toByteData(
        format: ImageByteFormat.png,
      );
      if (byteData == null || _disposed) return;

      final renderImage = await riveFactory.decodeImage(
        byteData.buffer.asUint8List(),
      );
      if (renderImage == null || _disposed) {
        renderImage?.dispose();
        return;
      }

      _viewModel.image(propertyName)!.value = renderImage;
      renderImage.dispose();
    } finally {
      imageInfo.dispose();
    }
  }

  void _cancelPendingImageLoad(String propertyName) {
    final pending = _pendingImageLoads.remove(propertyName);
    if (pending == null) return;
    pending.stream.removeListener(pending.listener);
    if (!pending.completer.isCompleted) {
      pending.completer.completeError(StateError('cancelled'));
    }
  }

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final propertyName in _pendingImageLoads.keys.toList()) {
      _cancelPendingImageLoad(propertyName);
    }
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}

class PropertyOfVmBackCard implements RiveViewModel {
  PropertyOfVmBackCard._(this._viewModel);

  factory PropertyOfVmBackCard.fromViewModel(ViewModelInstance viewModel) =
      PropertyOfVmBackCard._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<
    String,
    ({
      Completer<ImageInfo> completer,
      ImageStream stream,
      ImageStreamListener listener,
    })
  >
  _pendingImageLoads = {};

  final Map<String, StreamController<dynamic>> _streamControllers = {};
  // ignore: use_setters_to_change_properties
  void updateAssetBg(RenderImage value) =>
      _viewModel.image('assetBg')!.value = value;

  void resetAssetBg() => _viewModel.image('assetBg')!.value = null;

  Future<void> updateAssetBgFromImage({
    required Image image,
    required Factory riveFactory,
    required Rect? srcRect,
  }) => _updateImage(
    image: image,
    propertyName: 'assetBg',
    riveFactory: riveFactory,
    srcRect: srcRect,
  );

  Future<void> updateAssetBgFromImageProvider({
    required ImageProvider imageProvider,
    required Factory riveFactory,
  }) => _updateImageFromImageProvider(
    imageProvider: imageProvider,
    propertyName: 'assetBg',
    riveFactory: riveFactory,
  );

  bool get hasCustomBg => _viewModel.boolean('hasCustomBg')!.value;

  set hasCustomBg(bool value) =>
      _viewModel.boolean('hasCustomBg')!.value = value;

  Stream<bool> get hasCustomBgStream {
    return (_streamControllers['hasCustomBg'] ??= () {
          final controller = StreamController<bool>.broadcast();
          _streamControllers['hasCustomBg'] = controller;
          final property = _viewModel.boolean('hasCustomBg')!;
          void valueListener(bool value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<bool>;
  }

  Color get colorBg => _viewModel.color('colorBg')!.value;

  set colorBg(Color value) => _viewModel.color('colorBg')!.value = value;

  Stream<Color> get colorBgStream {
    return (_streamControllers['colorBg'] ??= () {
          final controller = StreamController<Color>.broadcast();
          _streamControllers['colorBg'] = controller;
          final property = _viewModel.color('colorBg')!;
          void valueListener(Color value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<Color>;
  }

  Future<void> _updateImage({
    required Image image,
    required String propertyName,
    required Factory riveFactory,
    required Rect? srcRect,
  }) async {
    final Rect fullImageRect = Rect.fromLTWH(
      0,
      0,
      image.width.toDouble(),
      image.height.toDouble(),
    );
    final Rect imageRect = srcRect ?? fullImageRect;

    Image? imageToRender;
    Picture? picture;
    try {
      if (imageRect != fullImageRect) {
        final PictureRecorder recorder = PictureRecorder();
        Canvas(recorder).drawImageRect(
          image,
          imageRect,
          Rect.fromLTWH(0, 0, imageRect.width, imageRect.height),
          Paint()..filterQuality = FilterQuality.medium,
        );
        picture = recorder.endRecording();
        imageToRender = await picture.toImage(
          imageRect.width.toInt(),
          imageRect.height.toInt(),
        );
      } else {
        imageToRender = image;
      }
      if (_disposed) return;
      final byteData = await imageToRender.toByteData(
        format: ImageByteFormat.png,
      );
      if (byteData == null || _disposed) {
        return;
      }
      final renderImage = await riveFactory.decodeImage(
        byteData.buffer.asUint8List(),
      );
      if (renderImage == null || _disposed) {
        renderImage?.dispose();
        return;
      }
      _viewModel.image(propertyName)!.value = renderImage;
      renderImage.dispose();
    } finally {
      picture?.dispose();
      if (imageToRender != image) {
        imageToRender?.dispose();
      }
    }
  }

  Future<void> _updateImageFromImageProvider({
    required ImageProvider imageProvider,
    required String propertyName,
    required Factory riveFactory,
  }) async {
    final completer = Completer<ImageInfo>();
    final stream = imageProvider.resolve(ImageConfiguration.empty);
    late final ImageStreamListener listener;
    listener = ImageStreamListener(
      (info, _) {
        stream.removeListener(listener);
        if (completer.isCompleted) {
          info.dispose();
        } else {
          completer.complete(info);
        }
      },
      onError: (error, stackTrace) {
        stream.removeListener(listener);
        if (completer.isCompleted) return;
        completer.completeError(error, stackTrace);
      },
    );

    _cancelPendingImageLoad(propertyName);
    _pendingImageLoads[propertyName] = (
      completer: completer,
      stream: stream,
      listener: listener,
    );
    stream.addListener(listener);

    final ImageInfo imageInfo;
    try {
      imageInfo = await completer.future;
    } catch (_) {
      return;
    } finally {
      _pendingImageLoads.remove(propertyName);
    }

    if (_disposed) {
      imageInfo.dispose();
      return;
    }

    try {
      final byteData = await imageInfo.image.toByteData(
        format: ImageByteFormat.png,
      );
      if (byteData == null || _disposed) return;

      final renderImage = await riveFactory.decodeImage(
        byteData.buffer.asUint8List(),
      );
      if (renderImage == null || _disposed) {
        renderImage?.dispose();
        return;
      }

      _viewModel.image(propertyName)!.value = renderImage;
      renderImage.dispose();
    } finally {
      imageInfo.dispose();
    }
  }

  void _cancelPendingImageLoad(String propertyName) {
    final pending = _pendingImageLoads.remove(propertyName);
    if (pending == null) return;
    pending.stream.removeListener(pending.listener);
    if (!pending.completer.isCompleted) {
      pending.completer.completeError(StateError('cancelled'));
    }
  }

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final propertyName in _pendingImageLoads.keys.toList()) {
      _cancelPendingImageLoad(propertyName);
    }
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}

class PropertyOfVmFrontCard implements RiveViewModel {
  PropertyOfVmFrontCard._(this._viewModel);

  factory PropertyOfVmFrontCard.fromViewModel(ViewModelInstance viewModel) =
      PropertyOfVmFrontCard._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<String, StreamController<dynamic>> _streamControllers = {};

  String get valueCard => _viewModel.string('valueCard')!.value;

  set valueCard(String value) => _viewModel.string('valueCard')!.value = value;

  Stream<String> get valueCardStream {
    return (_streamControllers['valueCard'] ??= () {
          final controller = StreamController<String>.broadcast();
          _streamControllers['valueCard'] = controller;
          final property = _viewModel.string('valueCard')!;
          void valueListener(String value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<String>;
  }

  CardSymbol get cardSymbol => CardSymbol.values.firstWhere(
    (e) => e.name == _viewModel.enumerator('cardSymbol')!.value,
  );

  set cardSymbol(CardSymbol value) =>
      _viewModel.enumerator('cardSymbol')!.value = value.name;

  Stream<CardSymbol> get cardSymbolStream {
    return (_streamControllers['cardSymbol'] ??= () {
          final controller = StreamController<CardSymbol>.broadcast();
          _streamControllers['cardSymbol'] = controller;
          final property = _viewModel.enumerator('cardSymbol')!;
          void valueListener(String value) => controller.add(
            CardSymbol.values.firstWhere((e) => e.name == value),
          );
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<CardSymbol>;
  }

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}

class VmCardViewModel implements RiveViewModel {
  VmCardViewModel._(this._viewModel);

  factory VmCardViewModel.fromViewModel(ViewModelInstance viewModel) =
      VmCardViewModel._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<String, StreamController<dynamic>> _streamControllers = {};

  PropertyOfVmBackCard get propertyOfVmBackCard {
    return PropertyOfVmBackCard.fromViewModel(
      _viewModel.viewModel('propertyOfVmBackCard')!,
    );
  }

  PropertyOfVmFrontCard get propertyOfVmFrontCard {
    return PropertyOfVmFrontCard.fromViewModel(
      _viewModel.viewModel('propertyOfVmFrontCard')!,
    );
  }

  bool get isFaceVisible => _viewModel.boolean('isFaceVisible')!.value;

  set isFaceVisible(bool value) =>
      _viewModel.boolean('isFaceVisible')!.value = value;

  Stream<bool> get isFaceVisibleStream {
    return (_streamControllers['isFaceVisible'] ??= () {
          final controller = StreamController<bool>.broadcast();
          _streamControllers['isFaceVisible'] = controller;
          final property = _viewModel.boolean('isFaceVisible')!;
          void valueListener(bool value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<bool>;
  }

  void triggerSwitchToBack() => _viewModel.trigger('switchToBack')!.trigger();

  void triggerSwitchToFace() => _viewModel.trigger('switchToFace')!.trigger();

  void triggerFlip() => _viewModel.trigger('triggerFlip')!.trigger();

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}
