// This file was generated by rive_viewmodel_generator
// Do not edit this file manually
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: unused_import
// ignore_for_file: depend_on_referenced_packages
import 'dart:async';
import 'dart:ui';
import 'package:flutter/painting.dart';
import 'package:rive/rive.dart';
import 'package:rive_viewmodel/rive_viewmodel.dart';

enum SymbolsCard { diamond, heart, spade, club }

enum BackCardStateMachine {
  SmBackCard('SmBackCard');

  const BackCardStateMachine(this.name);
  final String name;
}

enum LogoStateMachine {
  SmLogo('SmLogo');

  const LogoStateMachine(this.name);
  final String name;
}

enum BtStartStateMachine {
  SmButton('SmButton');

  const BtStartStateMachine(this.name);
  final String name;
}

enum FrontCardStateMachine {
  SmFrontCard('SmFrontCard');

  const FrontCardStateMachine(this.name);
  final String name;
}

enum BoardStateMachine {
  SmMiniGame('SmMiniGame');

  const BoardStateMachine(this.name);
  final String name;
}

enum CardStateMachine {
  SmCard('SmCard');

  const CardStateMachine(this.name);
  final String name;
}

enum MiniGameStateMachine {
  SmMiniGame('SmMiniGame');

  const MiniGameStateMachine(this.name);
  final String name;
}

enum MessagesStateMachine {
  SmMessages('SmMessages');

  const MessagesStateMachine(this.name);
  final String name;
}

enum BtRestartStateMachine {
  SmButton('SmButton');

  const BtRestartStateMachine(this.name);
  final String name;
}

sealed class _SealedArtboard {
  String get name;
}

abstract interface class DemoFlutterMinigameArtboard {
  static const backCard = _BackCard();
  static const logo = _Logo();
  static const btStart = _BtStart();
  static const frontCard = _FrontCard();
  static const board = _Board();
  static const card = _Card();
  static const miniGame = _MiniGame();
  static const messages = _Messages();
  static const btRestart = _BtRestart();
}

class _BackCard implements _SealedArtboard {
  const _BackCard();

  @override
  String get name => 'BackCard';

  BackCardStateMachine get SmBackCard => BackCardStateMachine.SmBackCard;
}

class _Logo implements _SealedArtboard {
  const _Logo();

  @override
  String get name => 'Logo';

  LogoStateMachine get SmLogo => LogoStateMachine.SmLogo;
}

class _BtStart implements _SealedArtboard {
  const _BtStart();

  @override
  String get name => 'BtStart';

  BtStartStateMachine get SmButton => BtStartStateMachine.SmButton;
}

class _FrontCard implements _SealedArtboard {
  const _FrontCard();

  @override
  String get name => 'FrontCard';

  FrontCardStateMachine get SmFrontCard => FrontCardStateMachine.SmFrontCard;
}

class _Board implements _SealedArtboard {
  const _Board();

  @override
  String get name => 'Board';

  BoardStateMachine get SmMiniGame => BoardStateMachine.SmMiniGame;
}

class _Card implements _SealedArtboard {
  const _Card();

  @override
  String get name => 'Card';

  CardStateMachine get SmCard => CardStateMachine.SmCard;
}

class _MiniGame implements _SealedArtboard {
  const _MiniGame();

  @override
  String get name => 'miniGame';

  MiniGameStateMachine get SmMiniGame => MiniGameStateMachine.SmMiniGame;
}

class _Messages implements _SealedArtboard {
  const _Messages();

  @override
  String get name => 'Messages';

  MessagesStateMachine get SmMessages => MessagesStateMachine.SmMessages;
}

class _BtRestart implements _SealedArtboard {
  const _BtRestart();

  @override
  String get name => 'BtRestart';

  BtRestartStateMachine get SmButton => BtRestartStateMachine.SmButton;
}

class VmCardViewModel implements RiveViewModel {
  VmCardViewModel._(this._viewModel);

  factory VmCardViewModel.fromViewModel(ViewModelInstance viewModel) =
      VmCardViewModel._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<
    String,
    ({
      Completer<ImageInfo> completer,
      ImageStream stream,
      ImageStreamListener listener,
    })
  >
  _pendingImageLoads = {};

  final Map<String, StreamController<dynamic>> _streamControllers = {};

  bool get isClickable => _viewModel.boolean('isClickable')!.value;

  set isClickable(bool value) =>
      _viewModel.boolean('isClickable')!.value = value;

  Stream<bool> get isClickableStream {
    return (_streamControllers['isClickable'] ??= () {
          final controller = StreamController<bool>.broadcast();
          _streamControllers['isClickable'] = controller;
          final property = _viewModel.boolean('isClickable')!;
          void valueListener(bool value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<bool>;
  }

  // ignore: use_setters_to_change_properties
  void updateAssetBg(RenderImage value) =>
      _viewModel.image('assetBg')!.value = value;

  void resetAssetBg() => _viewModel.image('assetBg')!.value = null;

  Future<void> updateAssetBgFromImage({
    required Image image,
    required Factory riveFactory,
    required Rect? srcRect,
  }) => _updateImage(
    image: image,
    propertyName: 'assetBg',
    riveFactory: riveFactory,
    srcRect: srcRect,
  );

  Future<void> updateAssetBgFromImageProvider({
    required ImageProvider imageProvider,
    required Factory riveFactory,
  }) => _updateImageFromImageProvider(
    imageProvider: imageProvider,
    propertyName: 'assetBg',
    riveFactory: riveFactory,
  );

  SymbolsCard get symbolsCard => SymbolsCard.values.firstWhere(
    (e) => e.name == _viewModel.enumerator('symbolsCard')!.value,
  );

  set symbolsCard(SymbolsCard value) =>
      _viewModel.enumerator('symbolsCard')!.value = value.name;

  Stream<SymbolsCard> get symbolsCardStream {
    return (_streamControllers['symbolsCard'] ??= () {
          final controller = StreamController<SymbolsCard>.broadcast();
          _streamControllers['symbolsCard'] = controller;
          final property = _viewModel.enumerator('symbolsCard')!;
          void valueListener(String value) => controller.add(
            SymbolsCard.values.firstWhere((e) => e.name == value),
          );
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<SymbolsCard>;
  }

  String get valueCard => _viewModel.string('valueCard')!.value;

  set valueCard(String value) => _viewModel.string('valueCard')!.value = value;

  Stream<String> get valueCardStream {
    return (_streamControllers['valueCard'] ??= () {
          final controller = StreamController<String>.broadcast();
          _streamControllers['valueCard'] = controller;
          final property = _viewModel.string('valueCard')!;
          void valueListener(String value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<String>;
  }

  bool get isFaceVisible => _viewModel.boolean('isFaceVisible')!.value;

  set isFaceVisible(bool value) =>
      _viewModel.boolean('isFaceVisible')!.value = value;

  Stream<bool> get isFaceVisibleStream {
    return (_streamControllers['isFaceVisible'] ??= () {
          final controller = StreamController<bool>.broadcast();
          _streamControllers['isFaceVisible'] = controller;
          final property = _viewModel.boolean('isFaceVisible')!;
          void valueListener(bool value) => controller.add(value);
          void onListen() => property.addListener(valueListener);
          void onCancel() => property.removeListener(valueListener);
          controller
            ..onListen = onListen
            ..onCancel = onCancel;
          return controller;
        }()).stream
        as Stream<bool>;
  }

  void triggerFlip() => _viewModel.trigger('triggerFlip')!.trigger();

  void triggerBump() => _viewModel.trigger('triggerBump')!.trigger();

  void triggerSwitchToBack() => _viewModel.trigger('switchToBack')!.trigger();

  void triggerSwitchToFace() => _viewModel.trigger('switchToFace')!.trigger();

  Future<void> _updateImage({
    required Image image,
    required String propertyName,
    required Factory riveFactory,
    required Rect? srcRect,
  }) async {
    final Rect fullImageRect = Rect.fromLTWH(
      0,
      0,
      image.width.toDouble(),
      image.height.toDouble(),
    );
    final Rect imageRect = srcRect ?? fullImageRect;

    Image? imageToRender;
    Picture? picture;
    try {
      if (imageRect != fullImageRect) {
        final PictureRecorder recorder = PictureRecorder();
        Canvas(recorder).drawImageRect(
          image,
          imageRect,
          Rect.fromLTWH(0, 0, imageRect.width, imageRect.height),
          Paint()..filterQuality = FilterQuality.medium,
        );
        picture = recorder.endRecording();
        imageToRender = await picture.toImage(
          imageRect.width.toInt(),
          imageRect.height.toInt(),
        );
      } else {
        imageToRender = image;
      }
      if (_disposed) return;
      final byteData = await imageToRender.toByteData(
        format: ImageByteFormat.png,
      );
      if (byteData == null || _disposed) {
        return;
      }
      final renderImage = await riveFactory.decodeImage(
        byteData.buffer.asUint8List(),
      );
      if (renderImage == null || _disposed) {
        renderImage?.dispose();
        return;
      }
      _viewModel.image(propertyName)!.value = renderImage;
      renderImage.dispose();
    } finally {
      picture?.dispose();
      if (imageToRender != image) {
        imageToRender?.dispose();
      }
    }
  }

  Future<void> _updateImageFromImageProvider({
    required ImageProvider imageProvider,
    required String propertyName,
    required Factory riveFactory,
  }) async {
    final completer = Completer<ImageInfo>();
    final stream = imageProvider.resolve(ImageConfiguration.empty);
    late final ImageStreamListener listener;
    listener = ImageStreamListener(
      (info, _) {
        stream.removeListener(listener);
        if (completer.isCompleted) {
          info.dispose();
        } else {
          completer.complete(info);
        }
      },
      onError: (error, stackTrace) {
        stream.removeListener(listener);
        if (completer.isCompleted) return;
        completer.completeError(error, stackTrace);
      },
    );

    _cancelPendingImageLoad(propertyName);
    _pendingImageLoads[propertyName] = (
      completer: completer,
      stream: stream,
      listener: listener,
    );
    stream.addListener(listener);

    final ImageInfo imageInfo;
    try {
      imageInfo = await completer.future;
    } catch (_) {
      return;
    } finally {
      _pendingImageLoads.remove(propertyName);
    }

    if (_disposed) {
      imageInfo.dispose();
      return;
    }

    try {
      final byteData = await imageInfo.image.toByteData(
        format: ImageByteFormat.png,
      );
      if (byteData == null || _disposed) return;

      final renderImage = await riveFactory.decodeImage(
        byteData.buffer.asUint8List(),
      );
      if (renderImage == null || _disposed) {
        renderImage?.dispose();
        return;
      }

      _viewModel.image(propertyName)!.value = renderImage;
      renderImage.dispose();
    } finally {
      imageInfo.dispose();
    }
  }

  void _cancelPendingImageLoad(String propertyName) {
    final pending = _pendingImageLoads.remove(propertyName);
    if (pending == null) return;
    pending.stream.removeListener(pending.listener);
    if (!pending.completer.isCompleted) {
      pending.completer.completeError(StateError('cancelled'));
    }
  }

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final propertyName in _pendingImageLoads.keys.toList()) {
      _cancelPendingImageLoad(propertyName);
    }
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}

class VmMiniGameViewModel implements RiveViewModel {
  VmMiniGameViewModel._(this._viewModel);

  factory VmMiniGameViewModel.fromViewModel(ViewModelInstance viewModel) =
      VmMiniGameViewModel._;

  final ViewModelInstance _viewModel;
  bool _disposed = false;

  @override
  bool get isDisposed => _disposed;

  final Map<String, StreamController<dynamic>> _streamControllers = {};

  void triggerSwapCards() => _viewModel.trigger('swapCards')!.trigger();

  void triggerWin() => _viewModel.trigger('win')!.trigger();

  void triggerLoose() => _viewModel.trigger('loose')!.trigger();

  void triggerReset() => _viewModel.trigger('reset')!.trigger();

  void triggerStartGame() => _viewModel.trigger('startGame')!.trigger();

  void triggerCardsShuffled() => _viewModel.trigger('cardsShuffled')!.trigger();

  VmCardViewModel get card1 {
    return VmCardViewModel.fromViewModel(_viewModel.viewModel('card1')!);
  }

  VmCardViewModel get card2 {
    return VmCardViewModel.fromViewModel(_viewModel.viewModel('card2')!);
  }

  VmCardViewModel get card3 {
    return VmCardViewModel.fromViewModel(_viewModel.viewModel('card3')!);
  }

  void bind(StateMachine stateMachine) =>
      stateMachine.bindViewModelInstance(_viewModel);

  @override
  void dispose() {
    _disposed = true;
    for (final controller in _streamControllers.values) {
      controller.close();
    }
    _streamControllers.clear();
    _viewModel.dispose();
  }
}
