import '../rive/card_step_demos.dart';
import 'betclic/betclic_code_slide.dart';

/// Step 1 — Design only: two artboards (BackCard, FrontCard) and an asset
/// that will later hold both faces. Dart still only loads the file and
/// renders a static artboard — no state machine, no bindings yet.
class RiveStep1Slide extends BetclicCodeSlide {
  RiveStep1Slide({super.key, super.pageNumber})
    : super(
        route: '/rive-step-1',
        title: 'Rive 1 — Design',
        subtitle:
            'Two artboards (BackCard, FrontCard) and a single asset that will '
            'hold both faces. Nothing animated yet — Dart only has to load '
            'the file and show one of the artboards.',
        codeLabel: 'STEP 01',
        code: _step1Code,
        result: const CardStep1Demo(),
      );
}

/// Step 2 — Animation + basic data binding: a new `card` artboard with the
/// `SmCard` state machine. The flip is driven by a `triggerFlip()` on a
/// strongly-typed view model.
class RiveStep2Slide extends BetclicCodeSlide {
  RiveStep2Slide({super.key, super.pageNumber})
    : super(
        route: '/rive-step-2',
        title: 'Rive 2 — Animation & data binding',
        subtitle:
            'Add a `card` artboard, the `SmCard` state machine and a view '
            'model. The flip animation is driven from Dart through a '
            'strongly-typed `triggerFlip()`.',
        codeLabel: 'STEP 02',
        code: _step2Code,
        result: const CardStep2Demo(),
      );
}

/// Step 3 — Customization: dedicated view models for the back (colour /
/// asset) and the front (value + suit), composed into the main `VmCard`.
class RiveStep3Slide extends BetclicCodeSlide {
  RiveStep3Slide({super.key, super.pageNumber})
    : super(
        route: '/rive-step-3',
        title: 'Rive 3 — Customization',
        subtitle:
            'A dedicated view model on each face: the back drives its '
            'colour or a bound image, the front drives the card value + suit. '
            'Both nest in the main `VmCard` — tweak it live from the HUD.',
        codeLabel: 'STEP 03',
        code: _step3Code,
        codeFontSize: 14,
        codeFlex: 5,
        resultFlex: 6,
        result: const CardStep3Demo(),
      );
}

const String _step1Code = '''
// One file, two artboards — switch between them by name.
// No state machine, no view model yet.
String artboard = 'FrontCard'; // or 'BackCard'

RiveWidgetBuilder(
  fileLoader: FileLoader.fromAsset('assets/card_step_1.riv'),
  artboardSelector: ArtboardSelector.byName(artboard),
  builder: (context, state) => switch (state) {
    RiveLoaded() => RiveWidget(
      controller: state.controller,
      fit: Fit.contain,
    ),
    RiveLoading() => const CircularProgressIndicator(),
    RiveFailed() => const Text('Could not load card'),
  },
);
''';

const String _step2Code = '''
// Generated by rive_viewmodel_generator from card_step_2.riv:
//   class VmCardViewModel { void triggerFlip(); ... }

void _onLoaded(RiveLoaded state) {
  final vmi = state.file
      .defaultArtboardViewModel(state.controller.artboard)!
      .createDefaultInstance()!;
  final vm = VmCardViewModel.fromViewModel(vmi);
  vm.bind(state.controller.stateMachine);

  // Drive the animation from Dart — the SM listens on the binding.
  vm.triggerFlip();
}
''';

const String _step3Code = '''
// Each face has its own view model, nested inside VmCard.
// Generated bindings keep colour, value and suit strongly typed.

final vm = VmCardViewModel.fromViewModel(vmi)
  ..bind(state.controller.stateMachine);

// Front face: value + suit.
vm.propertyOfVmFrontCard
  ..valueCard = 'A'
  ..cardSymbol = CardSymbol.heart;

// Back face: a solid colour…
vm.propertyOfVmBackCard
  ..colorBg = const Color(0xFFE10014)
  ..hasCustomBg = false;

// …or bind an image into the asset slot.
vm.propertyOfVmBackCard.hasCustomBg = true;
await vm.propertyOfVmBackCard.updateAssetBgFromImageProvider(
  imageProvider: const AssetImage('assets/logo.png'),
  riveFactory: Factory.rive,
);

vm.triggerFlip();
''';
